/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./app/**/*.php",
    "./public/**/*.html",
  ],
  safelist: [
    'w-16',
    'w-64',
    'bg-gradient-to-r',
    'from-blue-900',
    'via-blue-800',
    'to-blue-900',
    'text-white',
    'text-yellow-400',
    'text-blue-100',
    'text-blue-200',
    'bg-white/20',
    'bg-white/15',
    'bg-white/10',
    'backdrop-blur-sm',
    'border-white/30',
    'border-white/25',
    'border-white/20',
    'bg-yellow-500',
    'hover:bg-yellow-600',
    'text-blue-900',
    'hover:bg-white',
    'hover:text-blue-900',
    'border-2',
    'border-white',
    'border-yellow-400',
    'rounded-xl',
    'rounded-2xl',
    'rounded-full',
    'px-8',
    'py-4',
    'py-6',
    'py-16',
    'px-4',
    'p-6',
    'p-8',
    'mb-2',
    'mb-4',
    'mb-8',
    'mb-12',
    'mr-2',
    'text-4xl',
    'text-5xl',
    'text-3xl',
    'text-lg',
    'text-6xl',
    'w-20',
    'h-20',
    'w-5xl',
    'w-7xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-7xl',
    'grid-cols-2',
    'md:grid-cols-4',
    'gap-4',
    'gap-6',
    'flex',
    'flex-col',
    'sm:flex-row',
    'justify-center',
    'items-center',
    'text-center',
    'relative',
    'absolute',
    'inset-0',
    'z-10',
    'overflow-hidden',
    'min-h-screen',
    'mx-auto',
    'font-bold',
    'font-medium',
    'tracking-wide',
    'leading-relaxed',
    'transition-all',
    'duration-300',
    'transform',
    'hover:scale-105',
    'shadow-xl',
    'opacity-5',
    'opacity-50',
    'bg-opacity-50',
    'gray',
  ],
  theme: {
    extend: {
      fontFamily: {
        'sans': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'heading': ['Poppins', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
}
